### ISSUE TITLE
Include PSRD-Parser

### ISSUE THREAD

**Issue by christofsteel** [christofsteel/pySpellbook#10]
I recently stumbeled upon: @devonjones PSRD-Parser project. Maybe include improvements in my code or improve his parser

**Comment by christofsteel** [comment]
Gah.. found out, that it is GPL, so no including in PySpellbook.

**Comment by devonjones** [comment]
PSRD-Parser outputs json files and or sqlite databases.  Those are not covered by the gpl.  You maty find value in using the parser for it's output.

**Comment by devonjones** [comment]
The data files themselves are only covered by the OGL.  There's no reason to have to actually like the PSRD-Parser code into anything

**Comment by christofsteel** [comment]
Yes, but I initially thought of improving my parser. I still want to generate my own data, since I do not only use data from the PRD (And I already wrote it before stumbeling across your PSRD-Parser). And I want to ship my parser with my program. So no including your code ;) But maybe I check out your data format, so I can create a level of compatibility.

**Comment by devonjones** [comment]
https://github.com/devonjones/PSRD-Data
